services:
  nexus:
    image: ghcr.io/nitrexdesign/nexus:sha-6f23ebb
    ports:
      - "8080:8080"
    volumes:
      - nexus-data:/app/data
    environment:
      - PORT=8080
      - DB_PATH=/app/data/nexus.db
      - WEBAUTHN_RP_NAME=Nexus
      - WEBAUTHN_RP_ID=start.holroydnet.uk
      - WEBAUTHN_RP_ORIGIN=https://start.holroydnet.uk

volumes:
  nexus-data:
